/**
 * Mr. Clarke's Automated Briefing Generator — React Frontend
 * Uses CDN React + Babel Standalone (no Node.js needed)
 * Renders Tailwind HTML slides generated by the LLM
 */

const API_BASE = 'http://127.0.0.1:8000/api';

// ─── Components ───

function Header() {
    return (
        <header className="header">
            <h1 className="title">
                <span className="mr-clarkes">MR. CLARKE'S</span><br />
                <span className="briefing-gen">AUTOMATED BRIEFING GENERATOR</span>
            </h1>
            <p className="subtitle">PROJECT AV CLUB // SECURE CONNECTION ESTABLISHED</p>
        </header>
    );
}

function FileUploader({ files, onFilesChange }) {
    const dropRef = React.useRef(null);
    const inputRef = React.useRef(null);

    function handleFiles(fileList) {
        const newFiles = [...fileList].filter(f =>
            (f.name.endsWith('.pdf') || f.name.endsWith('.txt')) &&
            !files.some(existing => existing.name === f.name)
        );
        if (newFiles.length > 0) {
            onFilesChange([...files, ...newFiles]);
        }
    }

    function onDrop(e) {
        e.preventDefault();
        e.stopPropagation();
        dropRef.current.classList.remove('dragover');
        handleFiles(e.dataTransfer.files);
    }

    function onDragOver(e) {
        e.preventDefault();
        e.stopPropagation();
        dropRef.current.classList.add('dragover');
    }

    function onDragLeave(e) {
        e.preventDefault();
        dropRef.current.classList.remove('dragover');
    }

    return (
        <div className="upload-section">
            <h3>1. INGEST DATA</h3>
            <div
                className="drop-zone"
                ref={dropRef}
                onClick={() => inputRef.current.click()}
                onDrop={onDrop}
                onDragOver={onDragOver}
                onDragLeave={onDragLeave}
            >
                <svg className="upload-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                    <polyline points="17 8 12 3 7 8"></polyline>
                    <line x1="12" y1="3" x2="12" y2="15"></line>
                </svg>
                <p>Drag &amp; Drop transmission logs (PDF/TXT) or <span className="browse-btn">Browse files</span></p>
                <input
                    type="file"
                    ref={inputRef}
                    multiple
                    accept=".pdf,.txt"
                    hidden
                    onChange={(e) => handleFiles(e.target.files)}
                />
            </div>
            {files.length > 0 && (
                <ul className="file-list">
                    {files.map((f, i) => (
                        <li key={i}>
                            <span className="file-name">{f.name}</span>
                            <span className="file-size">[{(f.size / 1024).toFixed(1)} KB] - LOADED</span>
                        </li>
                    ))}
                </ul>
            )}
        </div>
    );
}

function QueryInput({ value, onChange }) {
    return (
        <div className="query-section">
            <h3>2. INITIATE QUERY</h3>
            <div className="input-wrapper">
                <span className="prompt-arrow">&gt;</span>
                <textarea
                    value={value}
                    onChange={(e) => onChange(e.target.value)}
                    placeholder="e.g. Explain wireless signal interference in the Upside Down..."
                    rows="3"
                />
            </div>
        </div>
    );
}

function StatusIndicator({ status, isLoading }) {
    return (
        <div className="status-indicator">
            <span className="status-text" style={{ color: status.startsWith('ERROR') ? '#ff5f56' : 'var(--text-terminal)' }}>
                {status}
            </span>
            {isLoading && <span className="loader"></span>}
        </div>
    );
}

function SlideViewer({ slides, currentSlide, onNext, onPrev, onFullscreen }) {

    // Keyboard navigation (← → arrow keys)
    React.useEffect(() => {
        function handleKey(e) {
            if (e.key === 'ArrowRight') onNext();
            if (e.key === 'ArrowLeft') onPrev();
        }
        window.addEventListener('keydown', handleKey);
        return () => window.removeEventListener('keydown', handleKey);
    }, [onNext, onPrev]);

    if (!slides || slides.length === 0) return null;

    return (
        <section className="output-panel">
            <div className="panel-header">
                <div className="lights">
                    <span className="light red"></span>
                    <span className="light yellow"></span>
                    <span className="light green"></span>
                </div>
                <span className="terminal-title">
                    PRESENTATION RENDERER — SLIDE {currentSlide + 1} / {slides.length}
                </span>
            </div>
            <div className="panel-body">
                <div className="preview-container" style={{ position: 'relative', overflow: 'hidden', background: '#0a0a1a' }}>
                    {/* key={currentSlide} forces React to DESTROY the old div and CREATE a brand new one.
                        This means every CSS animation replays from the start — guaranteed. */}
                    <div
                        key={currentSlide}
                        className="slide-container"
                        dangerouslySetInnerHTML={{ __html: slides[currentSlide] }}
                        style={{
                            width: '100%',
                            height: '100%',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            overflow: 'hidden',
                        }}
                    />
                </div>
                <div className="export-actions">
                    <button
                        className="secondary-btn"
                        onClick={onPrev}
                        disabled={currentSlide === 0}
                    >
                        ◀ PREV
                    </button>
                    <button
                        className="secondary-btn"
                        onClick={onFullscreen}
                    >
                        VIEW FULLSCREEN
                    </button>
                    <button
                        className="secondary-btn"
                        onClick={onNext}
                        disabled={currentSlide >= slides.length - 1}
                    >
                        NEXT ▶
                    </button>
                </div>
            </div>
        </section>
    );
}


// ─── Main App ───

function App() {
    const [files, setFiles] = React.useState([]);
    const [query, setQuery] = React.useState('');
    const [status, setStatus] = React.useState('AWAITING INPUT...');
    const [isLoading, setIsLoading] = React.useState(false);
    const [projectId, setProjectId] = React.useState(null);
    const [slides, setSlides] = React.useState([]);
    const [currentSlide, setCurrentSlide] = React.useState(0);
    const [hasGenerated, setHasGenerated] = React.useState(false);

    async function handleGenerate(e) {
        e.preventDefault();

        if (files.length === 0) {
            setStatus('ERROR: NO DATA SOURCES PROVIDED');
            setTimeout(() => setStatus('AWAITING INPUT...'), 3000);
            return;
        }
        if (!query.trim()) {
            setStatus('ERROR: QUERY REQUIRED');
            setTimeout(() => setStatus('AWAITING INPUT...'), 3000);
            return;
        }

        setIsLoading(true);
        setSlides([]);
        setCurrentSlide(0);

        try {
            // STEP 1: Upload files
            setStatus('UPLOADING & CHUNKING DOCUMENTS TO THE UPSIDE DOWN...');
            const formData = new FormData();
            files.forEach(f => formData.append('files', f));
            if (projectId) formData.append('project_id', projectId);

            const uploadRes = await fetch(`${API_BASE}/upload/`, { method: 'POST', body: formData });
            if (!uploadRes.ok) throw new Error('Upload failed');
            const uploadData = await uploadRes.json();
            const pid = uploadData.project_id;
            setProjectId(pid);

            // STEP 2: Generate or Update
            if (hasGenerated) {
                setStatus('UPDATING PRESENTATION... PRESERVING LAYOUTS...');
                const updateRes = await fetch(`${API_BASE}/update/`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ query: query, project_id: pid }),
                });
                if (!updateRes.ok) throw new Error('Update failed');
            } else {
                setStatus('COMMUNICATING WITH THE MIND FLAYER (LLM GENERATION)...');
                const genRes = await fetch(`${API_BASE}/generate/`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ query: query, project_id: pid }),
                });
                if (!genRes.ok) throw new Error('Generation failed');
            }

            // STEP 3: Fetch the individual slides from /api/project/
            setStatus('RENDERING SLIDES...');
            const projectRes = await fetch(`${API_BASE}/project/${pid}/`);
            if (!projectRes.ok) throw new Error('Failed to fetch project');
            const projectData = await projectRes.json();

            if (projectData.slides && projectData.slides.length > 0) {
                setSlides(projectData.slides);
                setCurrentSlide(0);
                setHasGenerated(true);
                setStatus(`TRANSMISSION COMPLETE. ${projectData.slides.length} SLIDES RENDERED.`);
            } else {
                throw new Error('No slides returned');
            }

        } catch (err) {
            console.error(err);
            setStatus(`ERROR: ${err.message.toUpperCase()}`);
            setTimeout(() => setStatus('AWAITING INPUT...'), 5000);
        } finally {
            setIsLoading(false);
        }
    }

    function openFullscreen() {
        if (!projectId) return;
        window.open(`${API_BASE}/render/${projectId}/`, '_blank');
    }

    return (
        <main className="container">
            <Header />

            <section className="interface-panel">
                <div className="panel-header">
                    <div className="lights">
                        <span className="light red"></span>
                        <span className="light yellow"></span>
                        <span className="light green"></span>
                    </div>
                    <span className="terminal-title">TERMINAL // HAWKINS_LAB</span>
                </div>
                <div className="panel-body">
                    <FileUploader files={files} onFilesChange={setFiles} />
                    <QueryInput value={query} onChange={setQuery} />
                    <div className="action-section">
                        <button className="hawkins-btn" onClick={handleGenerate} disabled={isLoading}>
                            <span className="btn-content">
                                {hasGenerated ? 'UPDATE BRIEFING DECK' : 'GENERATE BRIEFING DECK'}
                            </span>
                        </button>
                        <StatusIndicator status={status} isLoading={isLoading} />
                    </div>
                </div>
            </section>

            <SlideViewer
                slides={slides}
                currentSlide={currentSlide}
                onNext={() => setCurrentSlide(s => Math.min(s + 1, slides.length - 1))}
                onPrev={() => setCurrentSlide(s => Math.max(s - 1, 0))}
                onFullscreen={openFullscreen}
            />
        </main>
    );
}

// ─── Mount ───
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(React.createElement(App));
